# Generated by Django 5.2.8 on 2025-12-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='greeting',
        ),
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
