# Generated by Django 5.2.8 on 2025-12-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_home_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
