# Generated by Django 5.2.8 on 2025-12-23 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=7)),
                ('limit', models.PositiveIntegerField(default=20)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('extra_input', models.CharField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(default='gpt-5-mini', max_length=50)),
                ('feedback', models.TextField()),
                ('category_trend', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aifeedba_user_id_cf908f_idx')],
            },
        ),
    ]
