"""
Django settings for QuizRPG project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")  # quiz_back/.env

# ------------------------------------------------------------- Django core
# DEBUG를 가장 먼저 읽는다. 아래 설정들의 엄격도가 여기에 따라 갈린다.
DEBUG = env.bool("DJANGO_DEBUG", default=False)

if DEBUG:
    SECRET_KEY = env("DJANGO_SECRET_KEY", default="dev-only-insecure-key")
    ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[
        "http://localhost:5173", "http://127.0.0.1:5173",
        "http://localhost:4173", "http://127.0.0.1:4173",
    ])
else:
    # default 생략 → 키 자체가 없으면 ImproperlyConfigured로 기동 실패
    SECRET_KEY = env("DJANGO_SECRET_KEY")
    ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")
    CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

    # 키는 있는데 값이 비어 있는 경우까지 차단한다.
    # .env.example을 그대로 복사해 배포하는 실수가 실제 사고 유형이다.
    missing = [
        name for name, value in (
            ("DJANGO_SECRET_KEY", SECRET_KEY),
            ("DJANGO_ALLOWED_HOSTS", ALLOWED_HOSTS),
        )
        if not value
    ]
    if missing:
        raise ImproperlyConfigured(
            f"DEBUG=False 에서는 다음 환경변수가 반드시 설정되어야 합니다: {', '.join(missing)}"
        )

# 프록시(Cloudflare Tunnel → Nginx) 뒤에서 원래 요청 스킴을 인식한다.
# Cloudflare 가 HTTPS 를 종료하고 Nginx 에는 HTTP 로 들어오므로,
# 이 설정이 없으면 Django 가 요청을 HTTP 로 판단해 admin 로그인이 CSRF 오류로 실패한다.
# Nginx 가 X-Forwarded-Proto 를 전달해야 짝이 맞는다.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# API 는 TokenAuthentication 이라 CSRF 영향이 없으나, Django admin 은 세션 기반이다.
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# --------------------------------------------------------------------- AI
# 키가 없어도 앱은 기동된다. 호출 시 데모 모드로 축소 동작한다.
AI_BASE_URL    = env("AI_BASE_URL", default="https://api.openai.com/v1")
AI_API_KEY     = env("AI_API_KEY", default="")
AI_MODEL       = env("AI_MODEL", default="gpt-5-mini")
AI_DAILY_LIMIT = env.int("AI_DAILY_LIMIT", default=100)


# Application definition

INSTALLED_APPS = [
    'ai',
    'questions',
    'accounts',
    'game',
    "profiles.apps.ProfilesConfig",
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'corsheaders',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'QuizRPG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'QuizRPG.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}

if DATABASES["default"]["ENGINE"].endswith("sqlite3"):
    # DATABASE_URL의 상대경로는 실행 디렉터리 기준으로 해석된다.
    # gunicorn 등 작업 디렉터리가 다른 환경에서 엉뚱한 파일을 보지 않도록 BASE_DIR 기준으로 고정한다.
    db_name = DATABASES["default"]["NAME"]
    if db_name and not Path(db_name).is_absolute():
        DATABASES["default"]["NAME"] = str(BASE_DIR / db_name)

    # 동시성 옵션 — gunicorn 멀티 워커 환경에서 쓰기 락 경합 완화 (DR-1)
    DATABASES["default"]["OPTIONS"] = {
        "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        "transaction_mode": "IMMEDIATE",
        "timeout": 20,
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# collectstatic 수집 대상 경로. Nginx 가 이 디렉터리를 /static/ 으로 서빙한다.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# 로그인 토큰 사용 인증용
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # ai.throttles.AIRateThrottle 이 이 요율을 읽는다.
    # 전역 스로틀은 두지 않는다 — AI 엔드포인트에만 명시적으로 적용한다.
    'DEFAULT_THROTTLE_RATES': {
        'ai': '10/day',
    },
}

# 캐시 — 스로틀 카운터와 AI 전역 상한이 공유한다.
# 기본값인 locmem 은 프로세스마다 별도로 존재해 gunicorn 멀티 워커에서
# 상한이 워커 수만큼 늘어난다. DB 캐시는 워커 간에 공유된다.
#   테이블 생성: python manage.py createcachetable
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}

ACCOUNT_EMAIL_VERIFICATION = 'none'
